apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "davidnet-account-frontend.fullname" . }}-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "davidnet-account-frontend.fullname" . }}
          port: {{ .Values.service.port }}
  tls:
    secretName: {{ .Values.ingress.host }}-tls